<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Install-TensorFlow-2.0-alpha" data-toc-modified-id="Install-TensorFlow-2.0-alpha-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Install TensorFlow 2.0 alpha</a></span></li><li><span><a href="#Import-TensorFlow-and-Keras" data-toc-modified-id="Import-TensorFlow-and-Keras-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Import TensorFlow and Keras</a></span></li><li><span><a href="#Check-available-compute-devices" data-toc-modified-id="Check-available-compute-devices-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Check available compute devices</a></span></li><li><span><a href="#Set-the-device-placement-in-logs---visible-in-jupyter-console" data-toc-modified-id="Set-the-device-placement-in-logs---visible-in-jupyter-console-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Set the device placement in logs - visible in jupyter console</a></span></li><li><span><a href="#Observe-default-placement" data-toc-modified-id="Observe-default-placement-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Observe default placement</a></span></li><li><span><a href="#Place-on-GPU" data-toc-modified-id="Place-on-GPU-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Place on GPU</a></span></li><li><span><a href="#Place-on-CPU" data-toc-modified-id="Place-on-CPU-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Place on CPU</a></span></li><li><span><a href="#Safely-place-on-GPU" data-toc-modified-id="Safely-place-on-GPU-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Safely place on GPU</a></span></li></ul></div>

# TensorFlow and Keras 101 <a class="tocSkip">

In [1]:
# Imports to make notebook compatible with Python 2
from __future__ import absolute_import, division, print_function, unicode_literals

# Install TensorFlow 2.0 alpha

In [2]:
!pip install tensorflow-gpu==2.0.0-alpha0 

# Import TensorFlow and Keras

In [3]:
import tensorflow as tf
import tensorflow.keras as keras

In [4]:
import numpy as np

# Check available compute devices

In [5]:
from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 197133275586384869
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 227814228451621092
physical_device_desc: "device: XLA_GPU device"
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 12205684360897460308
physical_device_desc: "device: XLA_CPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 15588583015
locality {
  bus_id: 1
  links {
  }
}
incarnation: 10515997136820067847
physical_device_desc: "device: 0, name: Quadro P5000, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


# Set the device placement in logs - visible in jupyter console

In [6]:
tf.debugging.set_log_device_placement(True)

# Observe default placement

In [7]:
w = tf.Variable([.3], dtype=tf.float32,name='w')
b = tf.Variable([-.3], dtype=tf.float32,name='b')
    
@tf.function
def linear(x):
    return w * x + b

x = [1,2,3,4]

y=linear(x)

print("w:", w)
print("b:", b)
print("x:", x)
print("y:", y)

w: <tf.Variable 'w:0' shape=(1,) dtype=float32, numpy=array([0.3], dtype=float32)>
b: <tf.Variable 'b:0' shape=(1,) dtype=float32, numpy=array([-0.3], dtype=float32)>
x: [1, 2, 3, 4]
y: tf.Tensor([0.         0.3        0.6        0.90000004], shape=(4,), dtype=float32)


# Place on GPU

In [8]:
with tf.device('/gpu:0'):
    w = tf.Variable([.3], dtype=tf.float32,name='w')
    b = tf.Variable([-.3], dtype=tf.float32,name='b')
    
@tf.function
def linear(x):
    return w * x + b

x = [1,2,3,4]

y=linear(x)

print("w:", w)
print("b:", b)
print("x:", x)
print("y:", y)

w: <tf.Variable 'w:0' shape=(1,) dtype=float32, numpy=array([0.3], dtype=float32)>
b: <tf.Variable 'b:0' shape=(1,) dtype=float32, numpy=array([-0.3], dtype=float32)>
x: [1, 2, 3, 4]
y: tf.Tensor([0.         0.3        0.6        0.90000004], shape=(4,), dtype=float32)


# Place on CPU

In [9]:
with tf.device('/cpu:0'):
    w = tf.Variable([.3], dtype=tf.float32,name='w')
    b = tf.Variable([-.3], dtype=tf.float32,name='b')
    
@tf.function
def linear(x):
    return w * x + b

x = [1,2,3,4]

y=linear(x)

print("w:", w)
print("b:", b)
print("x:", x)
print("y:", y)

w: <tf.Variable 'w:0' shape=(1,) dtype=float32, numpy=array([0.3], dtype=float32)>
b: <tf.Variable 'b:0' shape=(1,) dtype=float32, numpy=array([-0.3], dtype=float32)>
x: [1, 2, 3, 4]
y: tf.Tensor([0.         0.3        0.6        0.90000004], shape=(4,), dtype=float32)


# Safely place on GPU

In [11]:
if tf.test.is_gpu_available():
    device = tf.test.gpu_device_name()
else:
    device = '/cpu:0'

print('Tensors on device ',device)
with tf.device(device):
    w = tf.Variable([.3], dtype=tf.float32,name='w')
    b = tf.Variable([-.3], dtype=tf.float32,name='b')
    
@tf.function
def linear(x):
    return w * x + b

x = [1,2,3,4]

y=linear(x)

print("w:", w)
print("b:", b)
print("x:", x)
print("y:", y)

Tensors on device  /device:GPU:0
w: <tf.Variable 'w:0' shape=(1,) dtype=float32, numpy=array([0.3], dtype=float32)>
b: <tf.Variable 'b:0' shape=(1,) dtype=float32, numpy=array([-0.3], dtype=float32)>
x: [1, 2, 3, 4]
y: tf.Tensor([0.         0.3        0.6        0.90000004], shape=(4,), dtype=float32)
