# TensorFlow and Keras 101 <a class="tocSkip">

<table align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/armando-fandango/<-path-to-repo>"><img src="https://colab.research.google.com/img/colab_favicon.ico" style="width:30px;" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/armando-fandango/<-path-to-repo>"><img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Logo.png" style="width:70px;" vspace="7px"/>View source on GitHub</a>
  </td>
</table>

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Install-TensorFlow-2.0-alpha" data-toc-modified-id="Install-TensorFlow-2.0-alpha-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Install TensorFlow 2.0 alpha</a></span></li><li><span><a href="#Import-TensorFlow-and-Keras" data-toc-modified-id="Import-TensorFlow-and-Keras-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Import TensorFlow and Keras</a></span></li><li><span><a href="#Customary-Hello-TensorFlow-!!!" data-toc-modified-id="Customary-Hello-TensorFlow-!!!-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Customary Hello TensorFlow !!!</a></span></li><li><span><a href="#TensorFlow-Core" data-toc-modified-id="TensorFlow-Core-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>TensorFlow Core</a></span><ul class="toc-item"><li><span><a href="#Creating-Tensors" data-toc-modified-id="Creating-Tensors-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Creating Tensors</a></span><ul class="toc-item"><li><span><a href="#Constant-Tensors" data-toc-modified-id="Constant-Tensors-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>Constant Tensors</a></span></li><li><span><a href="#Tensors-as-output-of-Operations" data-toc-modified-id="Tensors-as-output-of-Operations-4.1.2"><span class="toc-item-num">4.1.2&nbsp;&nbsp;</span>Tensors as output of Operations</a></span></li><li><span><a href="#Creating-Tensors-from-Existing-Objects" data-toc-modified-id="Creating-Tensors-from-Existing-Objects-4.1.3"><span class="toc-item-num">4.1.3&nbsp;&nbsp;</span>Creating Tensors from Existing Objects</a></span><ul class="toc-item"><li><span><a href="#0-Dimensional-Tensors-(Scalars)" data-toc-modified-id="0-Dimensional-Tensors-(Scalars)-4.1.3.1"><span class="toc-item-num">4.1.3.1&nbsp;&nbsp;</span>0-Dimensional Tensors (Scalars)</a></span></li><li><span><a href="#1-Dimensional-Tensors-(Vectors)" data-toc-modified-id="1-Dimensional-Tensors-(Vectors)-4.1.3.2"><span class="toc-item-num">4.1.3.2&nbsp;&nbsp;</span>1-Dimensional Tensors (Vectors)</a></span></li><li><span><a href="#2-Dimensional-Tensors-(Matrices)" data-toc-modified-id="2-Dimensional-Tensors-(Matrices)-4.1.3.3"><span class="toc-item-num">4.1.3.3&nbsp;&nbsp;</span>2-Dimensional Tensors (Matrices)</a></span></li><li><span><a href="#3-Dimensional-Tensors" data-toc-modified-id="3-Dimensional-Tensors-4.1.3.4"><span class="toc-item-num">4.1.3.4&nbsp;&nbsp;</span>3-Dimensional Tensors</a></span></li></ul></li><li><span><a href="#Creating-Tensors-from-Library-Functions" data-toc-modified-id="Creating-Tensors-from-Library-Functions-4.1.4"><span class="toc-item-num">4.1.4&nbsp;&nbsp;</span>Creating Tensors from Library Functions</a></span></li></ul></li><li><span><a href="#Variables" data-toc-modified-id="Variables-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Variables</a></span></li></ul></li><li><span><a href="#TensorFlow-Keras" data-toc-modified-id="TensorFlow-Keras-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>TensorFlow Keras</a></span></li><li><span><a href="#Training-model-using-Keras-Sequential-API" data-toc-modified-id="Training-model-using-Keras-Sequential-API-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Training model using Keras Sequential API</a></span></li><li><span><a href="#Advanced" data-toc-modified-id="Advanced-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Advanced</a></span></li><li><span><a href="#TensorBoard" data-toc-modified-id="TensorBoard-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>TensorBoard</a></span><ul class="toc-item"><li><span><a href="#Use-Jupyter-TensorBoard-plugin" data-toc-modified-id="Use-Jupyter-TensorBoard-plugin-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Use Jupyter TensorBoard plugin</a></span></li></ul></li></ul></div>

In [3]:
# Imports to make notebook compatible with Python 2
from __future__ import absolute_import, division, print_function, unicode_literals

# Install TensorFlow 2.0 alpha

In [10]:
!pip install tensorflow-gpu==2.0.0-alpha0

# Uncomment the command below if you would rather experiment with nightly version
#!pip install tf-nightly-gpu

# Import TensorFlow and Keras

In [11]:
import tensorflow as tf
import tensorflow.keras as keras

import numpy as np
import pandas as pd

import sys

print('Python : {}'.format(sys.version))
for package in tf, keras, np, pd:
    print('{} : {}'.format(package.__name__, package.__version__))

Python : 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
tensorflow : 2.0.0-dev20190421
tensorflow.keras : 2.2.4-tf
numpy : 1.16.2
pandas : 0.24.2


# Customary Hello TensorFlow !!!

In [12]:
hello = tf.constant('Hello TensorFlow 2 !!')
tf.print(hello)

Hello TensorFlow 2 !!


In [13]:
print(hello)

tf.Tensor(b'Hello TensorFlow 2 !!', shape=(), dtype=string)


# TensorFlow Core

## Creating Tensors

### Constant Tensors

In [14]:
c1 = tf.constant(5, name='x')
c2 = tf.constant(6.0, name='y')
c3 = tf.constant(7.0, dtype=tf.float32, name='z')
print('c1 (x): ', c1)
print('c2 (y): ', c2)
print('c3 (z): ', c3)

c1 (x):  tf.Tensor(5, shape=(), dtype=int32)
c2 (y):  tf.Tensor(6.0, shape=(), dtype=float32)
c3 (z):  tf.Tensor(7.0, shape=(), dtype=float32)


In [15]:
tf.print([c1, c2, c3])

[5, 6, 7]


### Tensors as output of Operations

In [16]:
op1 = tf.add(c2, c3)
op2 = tf.multiply(c2, c3)
print('op1 : ', op1)
print('op2 : ', op2)

op1 :  tf.Tensor(13.0, shape=(), dtype=float32)
op2 :  tf.Tensor(42.0, shape=(), dtype=float32)


In [17]:
tf.print('op1 : ', op1)
tf.print('op2 : ', op2)

op1 :  13
op2 :  42


### Creating Tensors from Existing Objects

#### 0-Dimensional Tensors (Scalars)

In [18]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)
print('tf_t : ', tf_t)

tf_t :  tf.Tensor(5.0, shape=(), dtype=float64)


#### 1-Dimensional Tensors (Vectors)

In [19]:
a1dim = np.array([1, 2, 3, 4, 5.99])
print("a1dim Shape : ", a1dim.shape)
tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)
print('tf_t : ', tf_t)
tf.print('tf_t[0] : ', tf_t[0])
tf.print('tf_t[2] : ', tf_t[2])

a1dim Shape :  (5,)
tf_t :  tf.Tensor([1.   2.   3.   4.   5.99], shape=(5,), dtype=float64)
tf_t[0] :  1
tf_t[2] :  3


#### 2-Dimensional Tensors (Matrices)

In [20]:
a2dim = np.array([(1, 2, 3, 4, 5.99),
                  (2, 3, 4, 5, 6.99),
                  (3, 4, 5, 6, 7.99)
                  ])
print("a2dim Shape : ", a2dim.shape)
tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)
print('tf_t : ', tf_t)
tf.print('tf_t[0][0] : ', tf_t[0][0])
tf.print('tf_t[1][2] : ', tf_t[1][2])

a2dim Shape :  (3, 5)
tf_t :  tf.Tensor(
[[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]], shape=(3, 5), dtype=float64)
tf_t[0][0] :  1
tf_t[1][2] :  4


#### 3-Dimensional Tensors

In [21]:
a3dim = np.array([[[1, 2],
                   [3, 4]
                   ],
                  [[5, 6],
                   [7, 8]
                   ]
                  ])
print("a3dim Shape : ", a3dim.shape)
tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)
print('tf_t : ', tf_t)
tf.print('tf_t[0][0][0] : ', tf_t[0][0][0])
tf.print('tf_t[1][1][1] : ', tf_t[1][1][1])

a3dim Shape :  (2, 2, 2)
tf_t :  tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0] :  1
tf_t[1][1][1] :  8


### Creating Tensors from Library Functions

In [22]:
a = tf.zeros((5,4))
print(a)
a = tf.ones((5,4))
print(a)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(5, 4), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(5, 4), dtype=float32)


## Variables

In [25]:
w = tf.Variable([.3], dtype=tf.float32,name='w')
print(w)
tf.print(w)

<tf.Variable 'w:0' shape=(1,) dtype=float32, numpy=array([0.3], dtype=float32)>
[0.3]


In [27]:
# Linear Model y = w * x + b

# Define model parameters
w = tf.Variable([.3], dtype=tf.float32,name='w')
b = tf.Variable([-.3], dtype=tf.float32,name='b')

# define model with inputs as arguments
@tf.function
def linear(x):
    return w * x + b

# define input array
x_in = [1,2,3,4]

# get output from the model by passing input
y=linear(x_in)

print("w:", w)
print("b:", b)
print("x_in:", x_in)
print("y:", y)

w: <tf.Variable 'w:0' shape=(1,) dtype=float32, numpy=array([0.3], dtype=float32)>
b: <tf.Variable 'b:0' shape=(1,) dtype=float32, numpy=array([-0.3], dtype=float32)>
x_in: [1, 2, 3, 4]
y: tf.Tensor([0.         0.3        0.6        0.90000004], shape=(4,), dtype=float32)


# TensorFlow Keras

# Training model using Keras Sequential API

In [17]:
mnist = keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [18]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [19]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test, y_test)

Epoch 1/5
60000/60000 [==============================] - 5s 76us/sample - loss: 0.2983 - accuracy: 0.9123
Epoch 2/5
60000/60000 [==============================] - 4s 67us/sample - loss: 0.1460 - accuracy: 0.9565
Epoch 3/5
60000/60000 [==============================] - 4s 65us/sample - loss: 0.1104 - accuracy: 0.9665
Epoch 4/5
60000/60000 [==============================] - 4s 70us/sample - loss: 0.0902 - accuracy: 0.9720
Epoch 5/5
10000/10000 [==============================] - 0s 42us/sample - loss: 0.0736 - accuracy: 0.9775


[0.07355862732266541, 0.9775]

# Advanced

In [20]:
!pip install tensorflow_datasets

  Using cached https://files.pythonhosted.org/packages/d9/b8/457ad44e8748fbe5021b4ca7e7d589b5852881bbb11bca4d947952a13558/tensorflow_datasets-1.0.1-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/08/b7/3fc74574aa9aff44491cce996711dd6094653c20d9e2800be4efb054e0da/tensorflow_metadata-0.13.0-py3-none-any.whl
    100% |████████████████████████████████| 51kB 3.8MB/s ta 0:00:01
    100% |████████████████████████████████| 829kB 14.2MB/s ta 0:00:01
  Stored in directory: /home/armando/.cache/pip/wheels/0c/61/d2/d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e
Successfully built future


In [21]:
import tensorflow_datasets as tfds
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

In [22]:
dataset, info = tfds.load('mnist', data_dir='gs://tfds-data/datasets', with_info=True, as_supervised=True)
mnist_train, mnist_test = dataset['train'], dataset['test']

def convert_types(image, label):
  image = tf.cast(image, tf.float32)
  image /= 255
  return image, label

mnist_train = mnist_train.map(convert_types).shuffle(10000).batch(32)
mnist_test = mnist_test.map(convert_types).batch(32)

class MyModel(Model):
  def __init__(self):
    super(MyModel, self).__init__()
    self.conv1 = Conv2D(32, 3, activation='relu')
    self.flatten = Flatten()
    self.d1 = Dense(128, activation='relu')
    self.d2 = Dense(10, activation='softmax')

  def call(self, x):
    x = self.conv1(x)
    x = self.flatten(x)
    x = self.d1(x)
    return self.d2(x)

model = MyModel()

loss_object = keras.losses.SparseCategoricalCrossentropy()

optimizer = keras.optimizers.Adam()

train_loss = keras.metrics.Mean(name='train_loss')
train_accuracy = keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')

test_loss = keras.metrics.Mean(name='test_loss')
test_accuracy = keras.metrics.SparseCategoricalAccuracy(name='test_accuracy')

@tf.function
def train_step(image, label):
  with tf.GradientTape() as tape:
    predictions = model(image)
    loss = loss_object(label, predictions)
  gradients = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(gradients, model.trainable_variables))

  train_loss(loss)
  train_accuracy(label, predictions)
    
@tf.function
def test_step(image, label):
  predictions = model(image)
  t_loss = loss_object(label, predictions)

  test_loss(t_loss)
  test_accuracy(label, predictions)

EPOCHS = 5

for epoch in range(EPOCHS):
  for image, label in mnist_train:
    train_step(image, label)

  for test_image, test_label in mnist_test:
    test_step(test_image, test_label)

  template = 'Epoch {}, Loss: {}, Accuracy: {}, Test Loss: {}, Test Accuracy: {}'
  print (template.format(epoch+1,
                         train_loss.result(),
                         train_accuracy.result()*100,
                         test_loss.result(),
                         test_accuracy.result()*100))


Epoch 1, Loss: 0.13769465684890747, Accuracy: 95.88166809082031, Test Loss: 0.05883735418319702, Test Accuracy: 98.1500015258789
Epoch 2, Loss: 0.09008178114891052, Accuracy: 97.28916931152344, Test Loss: 0.05430900305509567, Test Accuracy: 98.25
Epoch 3, Loss: 0.06765960901975632, Accuracy: 97.9383316040039, Test Loss: 0.05177422612905502, Test Accuracy: 98.33999633789062
Epoch 4, Loss: 0.05370677262544632, Accuracy: 98.35291290283203, Test Loss: 0.053110141307115555, Test Accuracy: 98.34750366210938
Epoch 5, Loss: 0.04471990838646889, Accuracy: 98.62566375732422, Test Loss: 0.05705774202942848, Test Accuracy: 98.29800415039062


# TensorBoard

In [23]:
# load TensorBoard notebook extension
%load_ext tensorboard.notebook

In [27]:
import os, datetime

logs_dir = "./tflogs"
os.makedirs(logs_dir, exist_ok=True)
#logs_dir = os.path.join(logs_dir, datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))

%tensorboard --logdir {logs_dir}

In [28]:
w = tf.Variable([.3], dtype=tf.float32,name='w')
b = tf.Variable([-.3], dtype=tf.float32,name='b')
    
@tf.function
def linear(x):
    return w * x + b

x = [1,2,3,4]

y=linear(x)

print("w:", w)
print("b:", b)
print("x:", x)
print("y:", y)

w: <tf.Variable 'w:0' shape=(1,) dtype=float32, numpy=array([0.3], dtype=float32)>
b: <tf.Variable 'b:0' shape=(1,) dtype=float32, numpy=array([-0.3], dtype=float32)>
x: [1, 2, 3, 4]
y: tf.Tensor([0.         0.3        0.6        0.90000004], shape=(4,), dtype=float32)


## Use Jupyter TensorBoard plugin

Install using the following commands:

pip install jupyter-tensorboard --upgrade

jupyter tensorboard enable --user